### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/nbdime#577]
https://github.com/jupyter/nbdime/releases/tag/3.0.0b1 was released on Jan 15. Unfortunately `conda-forge` doesn't really build pre-releases so there is no [`nbdime`](https://github.com/conda-forge/nbdime-feedstock/blob/master/recipe/meta.yaml#L1) compatible with JupyterLab 3 available for `conda` users.

It would be great if 3.0 could be released but it's currently hard for anyone else to chip in as there is no milestone or 3.0 label for issues so I'm opening this issue to keep track of what's required.

----

- [x] #566 - Add initial cell identifiers awareness
- [x] #574 - Use CDN for MathJax since offline file no longer present
- [x] #572 - Package labextension as federated extension 
- [x] #576 - Convert test from karma to jest

**Comment by dhirschfeld** [comment]
In https://github.com/jupyter/nbdime/pull/551#issuecomment-760404453 Vidar mentioned #553 as a blocker:
> *Turns out the new nbformat release also breaks CI (cf #553 ), but I'll cut a beta.*

**Comment by dhirschfeld** [comment]
Are there any other issues preventing a final release of 3.0?

**Comment by dhirschfeld** [comment]
Adding issues/prs referenced in:
https://github.com/jupyter/nbdime/issues/553#issuecomment-810054268

**Comment by vidartf** [comment]
It should be released on PyPI now (expect conda-forge in a few days). Let me know if there are any issues with the dist!
