### ISSUE TITLE
Migration to jupyterlab 4.0

### ISSUE THREAD

**Issue by HaudinFlorence** [jupyter/nbdime#659]
Hello,
@vidartf I am about to work on the migration of jupyterlab-git extension to jupyterlab 4.0 that depends on nbdime. Could you please give  a hint about what will be the strategy concerning nbdime: is it planed to keep the compatibility with previous versions of jupyterlab or not?
Many thanks in advance.
cc @fcollonval 

```[tasklist]
### Tasks
- [ ] https://github.com/jupyter/nbdime/issues/674
- [ ] https://github.com/jupyter/nbdime/issues/675
- [ ] https://github.com/jupyter/nbdime/issues/676
- [ ] https://github.com/jupyter/nbdime/issues/679
- [ ] https://github.com/jupyter/nbdime/issues/700
- [ ] https://github.com/jupyter/nbdime/issues/721
- [ ] https://github.com/jupyter/nbdime/issues/720
- [ ] https://github.com/jupyter/nbdime/pull/639
```

**Comment by vidartf** [comment]
Hi,
I'm not sure yet how much work will be needed to add support for lab 4.0. I believe the main things of importance are:
- any changes for lumino 2.0. If there are any breaking changes that are not easy to support both at the same time, it can be hard to support both 4.0 and 3.0 with the same version. However, I think the actual change is for nbdime to support 3 + 4 instead of the current 2 + 3.
- any changes related to the codemirror version bump. I don' think it should be an issue, but maybe there will be some conflict if we try to put both on the page at the same time?
- others??

**Comment by vidartf** [comment]
@fcollonval To try to rephrase myself: 

I want to add support for JupyterLab 4. The amount of work needed to do that depends on how many things we use break with the lumino 2.0 upgrade. If there are no breakages, we might even be able to support both 3.0 and 4.0.

Separately there is the question of the Codemirror change in JupyterLab 4.0. As of yet, the CM "DiffView/MergeView" code that I used as a basis for https://github.com/jupyter/nbdime/blob/master/packages/nbdime/src/common/mergeview.ts has not been ported to CM6, so I do not think that we can quickly change to using CM6 for nbdime. Hopefully, it should not be a problem for us to continue using CM5 in nbdime with JupyterLab 4.0 though. I'd be interested to hear your thoughts on whether both of them can be on the page at the same time.

**Comment by vidartf** [comment]
Or maybe the mergeview code has been ported now? https://github.com/codemirror/merge not sure if this is it?

**Comment by JohanMabille** [comment]
Looks like the MergeView for CM6 supports the two-way view only.

**Comment by CharlieJ15420** [comment]
Could you also add dependency support for jupyter_server 2.X.X please. Currently it only supports 1.X.X and lots of other extensions use 2.X.X. Thanks! :)

**Comment by vidartf** [comment]
Remaining tasks:
https://github.com/jupyter/nbdime/issues/674
https://github.com/jupyter/nbdime/issues/675
https://github.com/jupyter/nbdime/issues/676

**Comment by vidartf** [comment]
Note: An alpha version was released with #673

**Comment by fcollonval** [comment]
I started a task list in the first comment of this issue to track remaining issues to be addressed.

**Comment by fcollonval** [comment]
cc @krassowski - see tasks list; I proposed that contributor set them self as assignee when they start working on an issue to avoid conflict.

**Comment by fcollonval** [comment]
@vidartf @krassowski there are 4 nice to have PRs opened:
- https://github.com/jupyter/nbdime/pull/709
- https://github.com/jupyter/nbdime/pull/714
- https://github.com/jupyter/nbdime/pull/717
- https://github.com/jupyter/nbdime/pull/719

Mike also mentioned https://github.com/jupyter/nbdime/pull/639

Do we have other thing mandatory for having a new final release of nbdime?

**Comment by vidartf** [comment]
Not mandatory, but it would be nice to have https://github.com/jupyter/nbdime/pull/636 as well, but that needs rebasing (pick up autoformat changes, cm6 schanges) + needs some theming attention (new colors are not transparent, so struggle on themes, icons need to be reviewed if styleable by lab theme). Just mentioning for completeness.

**Comment by vidartf** [comment]
Also: https://github.com/jupyter/nbdime/issues/720

**Comment by vidartf** [comment]
https://github.com/jupyter/nbdime/issues/721

**Comment by krassowski** [comment]
Possibly #700 should not block the release, especially because after investigation it does **not** appear to be a regression due to CM6 migration?

**Comment by krassowski** [comment]
@vidartf @fcollonval It looks like we have everything that we wanted in for this release. Should we cut a beta or move straight to RC phase and announce intent to make a final release next week if nothing major comes up?

**Comment by fcollonval** [comment]
I'm 💯 on moving to rc and cut a final release as soon as possible.

**Comment by JohanMabille** [comment]
![chuck_norris_approves](https://github.com/jupyter/nbdime/assets/6754742/d170ae2c-ae1d-41c9-ae04-bda26557f14e)

**Comment by krassowski** [comment]
I tried to publish an RC using the releaser but it failed (https://github.com/jupyter/nbdime/actions/runs/6770648492) because of insufficient rights.

Can someone else can pick it up or help with permissions?

**Comment by fcollonval** [comment]
Thanks Mike

I updated your rights. And I'm gonna give it a try. I'm not sure the version of the npm packages are gonna be set up properly with the releaser :crossed_fingers:

**Comment by fcollonval** [comment]
... the JS packages are kept as alphas ... I'm gonna do a PR to migrate to rc.0. So they will be published as `rc.1`.

**Comment by fcollonval** [comment]
4.0.0rc0 has been released on [PyPI](https://pypi.org/project/nbdime/#history)
The NPM packages have version [rc.1](https://www.npmjs.com/package/nbdime?activeTab=versions)

The current limitations of the `scripts/bump_version.py` are:
- Version on the root `package.json` are not bumped because it is private and does not depend on the NPM packages
- NPM version does not switch between prerelease marker (alpha -> beta -> rc)

**Comment by vidartf** [comment]
Does the bump-version script ask for bumps independently for each target? Can we remove the private npm packages (webapp, root) as targets? It doesn't really do anything, and adds git noise. Or is that what you are saying is happening?

**Comment by vidartf** [comment]
FYI: I see the tag format changed from 3.2.1 --> v4.0.0rc1. Is that something we can normalize?

**Comment by fcollonval** [comment]
> Does the bump-version script ask for bumps independently for each target? Can we remove the private npm packages (webapp, root) as targets? It doesn't really do anything, and adds git noise. Or is that what you are saying is happening?

The script does not ask anything as it is run within GitHub jobs. It tries to be _smart_. But we may have to do something like lumino; forcing us to create a PR to bump the NPM package versions before releasing.

> FYI: I see the tag format changed from 3.2.1 --> v4.0.0rc1. Is that something we can normalize?

We can set [RH_TAG_FORMAT](https://github.com/jupyter-server/jupyter_releaser/blob/811e16f4194b161331599582ecb30b3de659ac58/jupyter_releaser/cli.py#L516) in that [environment](https://github.com/jupyter/nbdime/blob/554c2d34882c77ce48e85586f5db8fce93ed80d1/.github/workflows/publish-release.yml#L36), I think.

**Comment by fcollonval** [comment]
Could we define an ETA for the final release?

**Comment by vidartf** [comment]
I think we can release today or tomorrow, and then do any of the remaining nice to haves in a quick minor release after?

**Comment by vidartf** [comment]
> > FYI: I see the tag format changed from 3.2.1 --> v4.0.0rc1. Is that something we can normalize?
> 
> We can set [RH_TAG_FORMAT](https://github.com/jupyter-server/jupyter_releaser/blob/811e16f4194b161331599582ecb30b3de659ac58/jupyter_releaser/cli.py#L516) in that [environment](https://github.com/jupyter/nbdime/blob/554c2d34882c77ce48e85586f5db8fce93ed80d1/.github/workflows/publish-release.yml#L36), I think.

Not sure if that is possible, since it seems to be hardcoded other places as well: 
https://github.com/jupyter-server/jupyter_releaser/blob/811e16f4194b161331599582ecb30b3de659ac58/jupyter_releaser/lib.py#L39

**Comment by krassowski** [comment]
Do we want to wait for https://github.com/jupyter-server/jupyter_releaser/pull/536?

**Comment by vidartf** [comment]
If it's a short wait that would be nice. Not sure how easy/hard it would be to clean up manually?

**Comment by fcollonval** [comment]
I'm doing a last rc right now to test the new tag format.

**Comment by fcollonval** [comment]
Here it goes: https://github.com/jupyter/nbdime/releases/tag/4.0.0rc1

The tag is correct - I needed to pin a custom fork of the releaser to use the bug fix.  So I opened #738 as follow-up.

I'll do the final release this afternoon (around 4pm CET); let me know here if you want to postpone it.

**Comment by fcollonval** [comment]
:drum: i'm starting the final release

**Comment by fcollonval** [comment]
Ok final version has been released: https://github.com/jupyter/nbdime/releases/tag/4.0.0

**Comment by fcollonval** [comment]
But I think it is broken :boom: as CI is failing ---> investigating

**Comment by fcollonval** [comment]
Ok the error is due to the parsing of the version without release level.

I yanked 4.0.0 on PyPI.

**Comment by fcollonval** [comment]
[4.0.1](https://github.com/jupyter/nbdime/releases/tag/4.0.1) is all green

**Comment by JohanMabille** [comment]
![dance-crazy-carey-jim-carrey](https://github.com/jupyter/nbdime/assets/6754742/25b0773d-e62e-4617-adad-6c6148c6c24b)

**Comment by vidartf** [comment]
Thanks @fcollonval and congrats on first release of nbdime! 🎉
