### ISSUE TITLE
Support attachment field

### ISSUE THREAD

**Issue by vidartf** [jupyter/nbdime#99]
Version 4.1 of the notebook format added the `attachments` field to raw and markdown cells. Nbdime should also support this field.

### TODO:
 - [ ] Add server side predicates, differs and merge strategy for `attachments` to be similar to that of output mime bundles.
 - [ ] Add display capabilities in diff web view.
 - [ ] Add display capabilities in merge web view.

**Comment by vidartf** [comment]
First point fixed in #139.
